### ISSUE TITLE
use a stronger kdf

### ISSUE THREAD

**Issue by bazzargh** [rootVIII/openssl_encrypt_decrypt#1]
you're using the default key derivation function in openssl enc, which is notoriously weak-it's just a single round. This means brute force attempts would be extremely fast; also because you encrypt the entire json instead of just the random secrets, checking that a brute force decrypt has worked can be done locally in an instant instead of requiring a connection to aws. Consider at least using the -pbkdf2 flag, which uses 10,000 rounds to slow brute forcing attempts, and has been supported for a couple of years

https://github.com/openssl/openssl/commit/405988f2cca816fdfdf8ad62b1285dcf06822e85

Alternatively, use the python 'keyring' lib to store these secrets in gnome keyring (or other backends)

**Comment by rootVIII** [comment]
Well I think you may be right. However that may also be overkill for it's intended use.

Most developers save their AWS credentials as either environment variables or just by leaving in the rootkey.csv credentials file. Mine actually just sat in my .bashrc for a long time. Instead of leaving them there, I decided to just encrypt the rootkey.csv file so that any time I run an application with AWS/Boto 3 API calls, I will be prompted to decrypt the file with the password.  

Not only that, if someone were to get onto my local machine, my encrypted AWS API keys would be the least of my concerns, especially if the I-am users/groups are properly configured with their own credentials, deleting the current key and creating a new one is a very quick process. 

However I will most likely take your advice and add it soon
